services:
  api:
    container_name: evolution_api
    image: docker.io/evoapicloud/evolution-api:latest
    restart: always
    depends_on:
      - redis
      - evolution-postgres
    ports:
      - "8081:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
      - helpdesk_prod_network
    env_file:
      - .env
    environment:
      - CACHE_REDIS_URI=redis://evolution-redis:6379/6
    expose:
      - "8080"

  caddy:
    container_name: evolution_caddy
    image: docker.io/library/caddy:2
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./Docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - evolution-net
      - helpdesk_prod_network

  frontend:
    container_name: evolution_frontend
    image: docker.io/evoapicloud/evolution-manager:latest
    restart: always
    ports:
      - "3001:80"
    networks:
      - evolution-net
    volumes:
      - ./nginx.frontend.conf:/etc/nginx/conf.d/nginx.conf:ro

  redis:
    container_name: evolution-redis
    image: docker.io/library/redis:latest
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    networks:
      evolution-net:
        aliases:
          - evolution-redis
      helpdesk_prod_network:
        aliases:
          - evolution-redis
    expose:
      - "6379"

  evolution-postgres:
    container_name: evolution-postgres
    image: docker.io/library/postgres:15
    restart: always
    env_file:
      - .env
    command:
      - postgres
      - -c
      - max_connections=1000
      - -c
      - listen_addresses=*
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net
      - helpdesk_prod_network
    ports:
      - "5433:5432"

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
  helpdesk_prod_network:
    external: true